const menu = [
  {
    id: 1,
    title: 'CHICKEN SATAY',
    category: 'chicken',
    price: 15.99,
    img: './images/chickensatay.jpg',
    desc: `Marinated chicken on skewers served with peanut sauce and cucumber salad`,
  },
  {
    id: 2,
    title: 'SPRING ROLLS',
    category: 'vegetarian',
    price: 6.99,
    img: './images/springrolls.jpg',
    desc: `Homemade deep-fried vegan spring rolls served with plum sauce `,
  },
  {
    id: 3,
    title: 'CHICKEN PANANG CURRY',
    category: 'chicken',
    price: 13.99,
    img: './images/chickenpanangcurry.jpg',
    desc: `Bell pepper, green beans and basils in panang curry paste and coconut milk`,
  },
  {
    id: 4,
    title: 'PAD THAI',
    category: 'vegetarian',
    price: 13.99,
    img: './images/padthaiveg.jpg',
    desc: `Thin rice noodles, egg, bean sprout, onions, lime and ground peanut `,
  },
  {
    id: 5,
    title: 'BEEF PAD MA KHUR',
    category: 'beef',
    price: 13.99,
    img: './images/beefpadmakhur.jpg',
    desc: `Eggplant, onions, basil and bell peppers. This amazing dish will suprise you! `,
  },
  {
    id: 6,
    title: 'BEEF PAD PAK RUAM',
    category: 'beef',
    price: 18.99,
    img: './images/beefpadpakruam.jpg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'MANGO STICKY RICE',
    category: 'dessert',
    price: 6.99,
    img: './images/mangostickyrice.jpg',
    desc: `Fresh mango with sweet creamy sticky rice brings a sweet ending to any meal! `,
  },
  {
    id: 8,
    title: 'BANANA ROLLS',
    category: 'dessert',
    price: 6.99,
    img: './images/bananarolls.jpg',
    desc: `Deep fried bananas rolled in spring roll pastry topped with caramel and chocolate sauce `,
  },
  {
    id: 9,
    title: 'PAD THAI LEMONGRASS CHICKEN',
    category: 'chicken',
    price: 16.99,
    img: './images/padthailemongrasschicken.jpg',
    desc: `Pad Thai topped with marinated grilled chicken breast, served with peanut sauce and Thai chili lime sauce
    `,
  },
];
export default menu;
